services:
  - type: web
    name: keizaibot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python keizai.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
